services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: dressfy_frontend
    restart: unless-stopped
    environment:
      NODE_ENV: "production"
      NEXT_PUBLIC_API_URL: "http://api.estoque.app.fslab.dev"
      PORT: "3000"
    ports:
      - "3000:3000"
    networks:
      - dressfy_network

networks:
  dressfy_network:
    external: true

